---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-istio-csr
  namespace: cert-manager
  labels:
    app: cert-manager-istio-csr
    app.kubernetes.io/name: cert-manager-istio-csr
    app.kubernetes.io/instance: cert-manager-istio-csr
    app.kubernetes.io/version: "v0.12.0"
    app.kubernetes.io/managed-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-istio-csr
subjects:
- kind: ServiceAccount
  name: cert-manager-istio-csr
  namespace: cert-manager
